### ISSUE TITLE
Unable to configure in Docker Swarm via ENV vars

### ISSUE THREAD

**Issue by gregjan** [trellis-ldp/trellis-cassandra#30]
Thorntail startup succeeds, but I don't see Trellis start or any Trellis-related errors. I am running as follows:

the build:
$ mvn -P docker clean package

then within webapp/target:
$ java -jar webapp-0.0.1-SNAPSHOT-hollow-thorntail.jar webapp-0.0.1-SNAPSHOT.war

Console output: https://gist.github.com/gregjan/21c1824bbc2ba71675ec1573f0db410b

**Comment by ajs6f** [comment]
It's likely to be waiting for C*-- you don't seem to have given it any config to aim it at C*. Or is that running locally (localhost/9042)? Because it should find that...

Anyways, let's get some thicker logging-- can you add a logback config with DEBUG (look in the `src/test/resources` of any module for XML examples)? It's the usual `-Dlogback.configurationFile=/my/log/file.ext`.

**Comment by gregjan** [comment]
Here is a startup with DEBUG levels: https://gist.github.com/gregjan/588c7487749fea67ba028db49a5163fe
You are correct that I was running it without a backend at all. I would expect to see something in logs about trying and failing, but perhaps not. I will run it again in the full environment to see if that works.

**Comment by gregjan** [comment]
Huh, yeah no problem: https://gist.github.com/gregjan/37b85b876c684dc19826d849826f3786

You can see that I adjusted the root level to DEBUG but left the thrift and tamaya set to ERROR. It seemed to me that this would leave trellis logging at the DEBUG level..?

**Comment by ajs6f** [comment]
Arg, @gregjan can you try adding this system property to your invocation?

`-Dorg.jboss.logging.provider=slf4j`

I _think_ that should get you logging.

**Comment by ajs6f** [comment]
@gregjan Any logging joy?

**Comment by gregjan** [comment]
No luck yet: https://gist.github.com/gregjan/cea883a1192672cc78ff948c3cb6ff87
I am also going to try this jboss logging param on my server as docker image w/Cassandra deployed to see if that matters at all..

**Comment by gregjan** [comment]
Same result in the docker stack w/Cassandra available.. Reminder that I am running the hollow jar and pass the webapp jar in as the first parameter. Thorntail seems to recognize the webapp jar and do CDI things with it. I just never see the CassandraApplication light up, not does it respond to a GET request. Have you tried running it in this way? It was working before I pulled the last Tamaya-related update I think.

**Comment by gregjan** [comment]
Thanks for the context. Good to know why I am seeing the logging that I am. I am building and running this commit from Saturday:
```
commit 72cbb8c7579ca632e1368fd5b08954e1ec661f7c
Author: ajs6f <ajs6f@apache.org>
Date:   Sat Nov 24 16:15:58 2018 -0500

    Pruning dependencies
```

I will make sure that all is as I say with a clean build..

**Comment by gregjan** [comment]
Did a clean re-packaging of all the jars and wars. Confirmed the behavior. Are you able to duplicate this at all?

**Comment by ajs6f** [comment]
Working on just that-- I need to get back to an earlier commit of Trellis itself, since the new binary API means the commit we have in hand won't build any more.

**Comment by ajs6f** [comment]
@gregjan Are you giving explicit contact info  for C*, or relying on the defaults? Can I see your whole invocation?

**Comment by gregjan** [comment]
Relying on the defaults:

`jansen@X1:~/git/Drastic/trellis-cassandra/webapp/target$ java -Dorg.jboss.logging.provider=slf4j -Dlogback.configurationFile=../src/test/resources/logback-test.xml -jar webapp-0.0.1-SNAPSHOT-hollow-thorntail.jar webapp-0.0.1-SNAPSHOT.war`

**Comment by ajs6f** [comment]
Looks good, I have been able to reproduce, going to find out what's going on here.

**Comment by ajs6f** [comment]
Incidentally, part of what's going on is that the default values for config don't seem to be working. Whatever's going on here seems weirdly connected to Tamaya.

**Comment by ajs6f** [comment]
@gregjan can you please try the same invocation, but add explicit config for C*, i.e. `-Dcassandra.contactHost` or via env var?

**Comment by ajs6f** [comment]
Also, have you looked in the log file? Is that what you've been showing as gists, or just the STDOUT output?

**Comment by ajs6f** [comment]
To be clear, I suspect that part of what is happening here is that the awful JBoss Logging crap is sitting on the console. When I reproduce, I get no logging on-screen, but I _do_ get correct logging in the files. Not sure how the hell that is happening, but it is definitely happening.

**Comment by ajs6f** [comment]
Confirming that in my reproduction, the logs are appearing very nicely in the file appender. Can you check that?

**Comment by gregjan** [comment]
Aha! let me check.

**Comment by gregjan** [comment]
Okay, I modified log.dir to make it simply "logs" and created that directory. Then I ran it again and it did create a system.log file there! Yay! However, that log file is empty. Darn!

**Comment by ajs6f** [comment]
Have you fired a request yet? CDI is _very _lazy. Nothing happens until it has to.

**Comment by ajs6f** [comment]
Conforming also that in the absence of correct C* connection config, I get the appropriate 
```
DEBUG [Cassandra Connection Maker] 2018-11-27 16:05:58,171 CassandraContext.java:159 - Still looking for connection to localhost
```
logging.

**Comment by gregjan** [comment]
No dice on that, connection refused. Log file remains empty. (8080 is default port, right?)

**Comment by gregjan** [comment]
You see that DEBUG statement in your log file?

**Comment by ajs6f** [comment]
Nope, the default port is 0 (select the first available port). Should we go with 8080? Happy to do that (file a ticket please).

Otherwise, just for the moment, add `-Dswarm.http.port=8080` to your invocation to make it so.

**Comment by ajs6f** [comment]
Oh, yeah. I'm seeing as much logging as I want. I think you need to get the right port, then fire a request (which boots CDI) and then you'll start seeing stuff in the file. Until all that CDI comes up, there is really no app to log.

**Comment by gregjan** [comment]
oh man.. I hit 40691 instead and stuff is happening. More soon.

**Comment by gregjan** [comment]
Okay, I just had to hit the endpoint correctly.. The logging is on the console as well now.

**Comment by ajs6f** [comment]
"stuff is happening". So many tickets I've worked where that was either the best or worst thing to hear.

**Comment by ajs6f** [comment]
Holy snozzwangler! So the real issue here is "Adam chooses default ports like a drunken chimp."

**Comment by gregjan** [comment]
Heh. How can I set a non-default? 40691 was nowhere in the codebase, so I assume that's plucked out the air by Thorntail.

**Comment by ajs6f** [comment]
No, by Java-- if you open a socket at 0, Java will search for the next available one. You can immediately use that `-Dswarm.http.port=8080` bit I put above. I will research better ways. 

It's tricky, because you generally don't want to control ports at the application level-- you let the container do that. So neither Thorntail nor any other such gear is really set up to let that happen easily. We may have to use the ways that Thorntail provides, which allow a default of our choice, a CLI override using that system property, and a persistent config file in YAML for such framework properties.

**Comment by gregjan** [comment]
Ha! This is fine. I'll file a PR for the new docker_command.sh with the new particulars.

**Comment by ajs6f** [comment]
I'm leaving this ticket open for that `docker_command.sh` PR, but otherwise I think we're good here?

**Comment by gregjan** [comment]
Since this issue turned into a thread about Trellis C* startup parameters, I'll leave this here. I haven't looked into the cause yet, but I've found that the environment variables don't impact the configuration yet. I can set address and port via -Dcassandra.contactPort=9042, but not via an env setting of CASSANDRA_CONTACT_PORT=9042. I am working around this for the moment in my startup script, so it is not blocking anything. There must be an additional flag that Tamaya needs in order to read the env?

**Comment by gregjan** [comment]
The documentation here (http://tamaya.apache.org/documentation/core.html) includes this line:

> Read environment properties and add them prefixed with env.

**Comment by gregjan** [comment]
I'll try adding env. to the property source names in the code annotations and see if that works.

**Comment by ajs6f** [comment]
Just catching up-- please do try. I'm weirded out by this because I used the env var names as we doc them to successfully start t-c*, but it's certainly possible that I didn't do that correctly.

I need to write some tests for this, of course. Okay with me changing the title of this ticket to something like "Unable to configure with env vars"?

**Comment by gregjan** [comment]
Yes, sounds good.

**Comment by gregjan** [comment]
I have tried the "env." and "env:" prefixes, but saw no change. The docs are slim on examples of using environment variables, outside of the defaultValue field. Note sure if perhaps we are supposed to be using the full "${CASSANDRA_CONTACT_ADDRESS}" form as the property name. That form seems more like a value form than a name for a source.

**Comment by ajs6f** [comment]
Let me look up something from Tamaya's codebase. I don't see how `${CASSANDRA_CONTACT_ADDRESS}` could make sense either.

**Comment by acoburn** [comment]
I think the issue here is the distinction between "system properties" (e.g. `cassandra.contactPort`) and "environment properties" (e.g. `CASSANDRA_CONTACT_PORT`). If I'm not mistaken, tamaya is set up to read the _system property_. As for prefixing them with `env`, the _code_ would need to prefix those values with `env`, not your invocation. That is, the Tamaya code would need to accept `env.CASSANDRA_CONTACT_PORT`, which is not the case.

**Comment by gregjan** [comment]
Sure, my finding is that this will work:
```
OPTS="-Dcassandra.contactAddress=$CASSANDRA_CONTACT_ADDRESS -Dcassandra.contactPort=$CASSANDRA_CONTACT_PORT"
java $OPTS -Dswarm.http.port=8080 -Dorg.jboss.logging.provider=slf4j -Dlogback.configurationFile=/logback-docker.xml -Djava.net.preferIPv4Stack=true -jar webapp-hollow-thorntail.jar webapp.war
```

Whereas this invocation will cause C* connection to revert to default localhost:
```
java -Dswarm.http.port=8080 -Dorg.jboss.logging.provider=slf4j -Dlogback.configurationFile=/logback-docker.xml -Djava.net.preferIPv4Stack=true -jar webapp-hollow-thorntail.jar webapp.war
```

Both of these are running w/in the docker container in a script. I used that OPTS trick to test the java properties approach b/c I wanted to double-check that the environment variables were set properly in that precise context.

**Comment by ajs6f** [comment]
Hm, ok, that's exactly what I would expect-- where in the second invoc are you actually setting the env vars? Did you `export` them somewhere beforehand, or something like that?

**Comment by gregjan** [comment]
Yeah, they are supplied from outside of the container via a docker stack deploy. I was also able to verify the env in the running container by starting an sh session in the running trellis-cassandra container and then looking at env.

**Comment by ajs6f** [comment]
Yeah, that makes sense. Ok, I'm occupied for a bit, but I'll start reproducing this in an hour or so-- cool?

**Comment by gregjan** [comment]
In particular the env variables are set in a docker compose file:

```
version: "3"
# https://forums.docker.com/t/cassandra-on-docker-swarm/27923/3 - placement ideas
# https://github.com/thelastpickle/docker-cassandra-bootstrap - monitoring/grafana, other docker details
services:
  trellis-cassandra:
    image: trellisldp/trellis-cassandra:0.0.1-SNAPSHOT
    ports:
      - "10080:8080"
    environment:
      CASSANDRA_CONTACT_ADDRESS: cassandra-1
      CASSANDRA_CONTACT_PORT: 9042
      CASSANDRA_MAX_CHUNK_SIZE: 1048576
      CASSANDRA_BINARY_READ_CONSISTENCY: ONE
      CASSANDRA_BINARY_WRITE_CONSISTENCY: ONE
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 20
        window: 120s
#    command: ["java", "--illegal-access=warn", "-jar", "/opt/trellis/trellis.jar", "server", "/opt/trellis/config.yml"]
    links:
      - cassandra-1
      - cassandra-2
      - cassandra-3
#      - cassandra-4
    depends_on:
      - cassandra-1
      - cassandra-2
      - cassandra-3
#      - cassandra-4
  cassandra-1:
    image: cassandra
    environment:
      CASSANDRA_BROADCAST_ADDRESS: cassandra-1
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        constraints:
        - node.labels.host==ciber-vs1
    volumes:
      - /export/testdata/ldp/cassandra:/var/lib/cassandra
  cassandra-2:
    image: cassandra
    environment:
      CASSANDRA_BROADCAST_ADDRESS: cassandra-2
      CASSANDRA_SEEDS: cassandra-1
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        constraints:
        - node.labels.host==ciber-vs2
    depends_on:
      - cassandra-1
    volumes:
      - /export/testdata/ldp/cassandra:/var/lib/cassandra
  cassandra-3:
    image: cassandra
    environment:
      CASSANDRA_BROADCAST_ADDRESS: cassandra-3
      CASSANDRA_SEEDS: cassandra-1
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        constraints:
        - node.labels.host==ciber-vs3
    depends_on:
      - cassandra-2
    volumes:
      - /export/testdata/ldp/cassandra:/var/lib/cassandra
  cassandra-init:
    image: gregjan/trellis-cassandra-init
    depends_on:
      - cassandra-3
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
    command: cqlsh cassandra-1 -f /load.cql
```
